psi_interval: 2.0
cgroup_mount: "/sys/fs/cgroup"
vendor: "generic"  # admin, generic
thresholds:
  low: 0.4
  medium: 0.6
  high: 0.8
  critical: 1.0
weights:
  cpu: 2
  memory: 7
  io: 1
weights_top:
  cpu: 2
  memory: 7
  io: 1
all_apps:
  - name: "Calculator"  # Calculator
    id: "org.gnome.Calculator.desktop"  # org.gnome.Calculator.desktop
    commandline: "gnome-calculator"  # gnome-calculator
  - name: "vlc" # VLC media player
    id: "vlc.desktop"
    commandline: "/usr/bin/vlc"
  - name: "Text Editor" # Text Editor
    id: "org.gnome.TextEditor.desktop"
    commandline: "gnome-text-editor %U"
monitor_apps:  # Applications to monitor for some specific handling
  - name: "Calculator"
    bpf_name: ["gnome-calculator"]
  - name: "VLC media player"
    bpf_name: ["vlc"]
  - name: "System Monitor"
    bpf_name: ["gnome-system-monitor"]
  - name: "Text Editor"
    bpf_name: ["gnome-text-editor"]
blacklist:
  - systemd
  - kworker
  - dbus
cooldown_time: 15
cpu_busy_threshold: 90
memory_busy_threshold: 90
disk_utilization_threshold: 90
regular_update_sys_pressure_time: 5
workloads:
  - name: "critical"
    priority: 100
    cpu_weight: 300
    memory_min: "2G"
    io_weight: 500
  - name: "best-effort"
    priority: 20
    cpu_weight: 50
    memory_min: "0"
    io_weight: 100
balance_service:
  url: "http://127.0.0.1"
  port: 9001
  get_priority: "app/get_priority_data"
app_priority:
  critical: 100
  high: 80
  medium: 50
  low: 20
enable_network_control: true # 是否启用流量控制
network_thresholds:
  low: 0.3
  medium: 0.5
  high: 0.7
  critical: 0.9
network_interface: "enp1s0" # 请根据实际情况修改为你的网络接口名称
network_bandwidth_kbit: 100000  # 当前设置为100Mbps（小了10倍）便于测试，请根据实际带宽调整，单位为kbit/s
config_network_bw:  # kbit/s, 不同优先级对应的带宽范围设置, 为了便于测试都缩小了10倍
  system:
    min: 5000
    max: 10000
  critical:
    min: 60000
    max: 90000
  high:
    min: 30000
    max: 80000
  low:
    min: 10000
    max: 80000
network_burst_map:
  critical: "64k"
  high: "32k"
  low: "16k"
  system: "8k"
network_system_ports:
  - 22
  - 53
  - 80
  - 443
  - 123
testing_network_app:
  - app_name: "iperf"
    app_cgroup: "session-1879.scope"
    priority: "critical"
